config/routes.rb
Parte::Application.routes.draw do
  
  namespace :production do
    resources :entities
    resources :projects
    match 'apgraficos/start' => 'apgraficos#start', via: [:get, :post]
    resources :tareoscolumnas
    resources :tareosfilas
    resources :tareosgruposdetrabajos
    get 'inicios/index' => 'inicios#index'
    get 'inicios' => 'inicios#index'
    resources :vequipodays
    match 'importalistas/import' => 'importalistas#import', via: [:get, :post]
    resources :importalistas
    resources :vpartidas
    resources :dias
    resources :tipodedias
    resources :semanas
    resources :mes
    resources :years
    resources :maquinariaequipodetalles
    resources :maquinariaequiporesumenes
    resources :maquinariaequipos
    match 'reportofmachineries/ver_resumen_equipo' => 'reportofmachineries#ver_resumen_equipo', via: [:get, :post]
    match 'reportofmachineries/ver_resumen_subcontratista' => 'reportofmachineries#ver_resumen_subcontratista', via: [:get, :post]
    match 'reportofmachineries/aprobar', via: [:get, :post]
    match 'reportofmachineries/resumen_equipodesubcontrato', via: [:get, :post]
    match 'reportofmachineries/resumen_subcontratista', via: [:get, :post]
    match 'reportofmachineries/valorizar_consulta', via: [:get, :post]
    match 'reportofmachineries/primero', via: [:get, :post]
    match 'reportofmachineries/valorizar_consulta_guardar' => 'reportofmachineries#valorizar_consulta_guardar', via: [:get, :post]  
    resources :reportofmachineries
    match 'reportofequipments/values_combo2/:id' => 'reportofequipments#values_combo2#:id', via: [:get, :post]
    match 'reportofequipments/primero' => 'reportofequipments#primero', via: [:get, :post] 
    resources :reportofequipments
    resources :fueltypes
    resources :vequipos
    resources :vmanodeobras
    resources :equipmentregisters
    resources :partofequipments
    get 'partofequipments/values_equiposdesubcontrato/:id' => 'partofequipments#values_equiposdesubcontrato#:id'
    get 'partofequipments/values_equiposdesubcontrato' => 'partofequipments#values_equiposdesubcontrato'  
    get 'partofequipments/values_unidades/:id' => 'partofequipments#values_unidades#:id'
    get 'partofequipments/values_unidades' => 'partofequipments#values_unidades'
    resources :inputofequipments
    resources :units
    resources :equipmentincludeds
    post '/equipmentsofsubcontracts/create' => 'equipmentsofsubcontracts#create'
    post '/equipmentsofsubcontracts/update' => 'equipmentsofsubcontracts#update'
    delete '/equipodesubcontratos/destroy' => 'equipodesubcontratos#destroy'
    match '/equipmentsofsubcontracts/new/:id' => 'equipmentsofsubcontracts#new#:id', via: [:get, :post]
    resources :equipmentsofsubcontracts
    match 'subcontractofequipments/ver_equipos/:id' => 'subcontractofequipments#ver_equipos#:id', via: [:get, :post]
    match 'subcontractofequipments/equipoadd/:id' => 'subcontractofequipments#equipoadd#:id', via: [:get, :post]
    match 'subcontractofequipments/equipoedit/:id' => 'subcontractofequipments#equipoedit#:id', via: [:get, :post]
    get 'subcontractofequipments/equipover/:id' => 'subcontractofequipments#equipover#:id'
    resources :subcontractofequipments
    resources :groupsofworks
    resources :teacherofworks
    resources :chiefoffronts
    resources :fronts
    resources :relaciones
    resources :subcategorias
    resources :categorias
    #resources :entities
    resources :workers
    resources :catalogofworks
    resources :catalogcategoryworks
    get 'partdayliofpeople/values_partidasdecontrol/:id' => 'partdayliofpeople#values_partidasdecontrol#:id'
    resources :partdayliofpeople
    resources :subcontracts
    resources :catalogodeinsumos
    resources :inputs
    resources :suppliers
    resources :valesdeconsumos
    get 'itemsofcontrols/mostrar/:id' => 'itemsofcontrols#mostrar#:id'
    get 'itemsofcontrols/valuesubfase/:id' => 'itemsofcontrols#valuesubfase#:id'
    get 'partworks/values_opcion/:id' => 'partworks#values_opcion#:id'
    get 'partdayliofpeople/values_opcion/:id' => 'partdayliofpeople#values_opcion#:id'
    get 'partofequipments/values_opcion/:id' => 'partofequipments#values_opcion#:id'
    get 'partworks/values_partidasdecontrol/:id' => 'partworks#values_partidasdecontrol#:id'
    get 'partworks/values_tipodevale/:id' => 'partworks#values_tipodevale#:id'
    get 'partworks/values_tipodevale' => 'partworks#values_tipodevale'
    get 'partworks/values_partidaunidad/:id' => 'partworks#values_partidaunidad#:id'
    resources :itemsofcontrols
    resources :subsectors
    resources :sectors
    get "subfases/migrar"
    resources :subphases
    resources :phases
    match "listcategories/importar_partidas" => 'listcategories#importar_partidas', via: [:get, :post]
    resources :listcategories
    get "lists/migrar"
    resources :lists do
      collection { 
        match :import, via: [:get, :post] 
      }
    end    
    resources :items
    resources :partworks
    
    match 'valuations/equipo_days' => 'valuations#equipo_days', via: [:get, :post]
    match 'valuations/ver_equipodays' => 'valuations#ver_equipodays', via: [:get, :post]
    match 'valuations/ver_valorizacion_manodeobra' => 'valuations#ver_valorizacion_manodeobra', via: [:get, :post]
    match 'valuations/ver_valorizacion_equipos' => 'valuations#ver_valorizacion_equipos', via: [:get, :post]
    match 'valuations/valorizacion_manodeobras' => 'valuations#valorizacion_manodeobras', via: [:get, :post]
    match 'valuations/valorizacion_equipos' => 'valuations#valorizacion_equipos', via: [:get, :post]
    match 'valuations/ver_valorizacion_partidas' => 'valuations#ver_valorizacion_partidas', via: [:get, :post]
    match 'valuations/valorizacion_partidas' => 'valuations#valorizacion_partidas', via: [:get, :post]
    match 'valuations/valorizacion_uno' => 'valuations#valorizacion_uno', via: [:get, :post]
    match 'valuations/produccion_fecha' => 'valuations#produccion_fecha', via: [:get, :post]
    post 'valuations/produccion_procesar' => 'valuations#produccion_procesar'
    match 'valuations/valorizacion_guardar' => 'valuations#valorizacion_guardar', via: [:get, :post]
    post 'valuations/valorizacion_aprobar' => 'valuations#valorizacion_aprobar'
    resources :valuations
    get 'tareos/desaprobar' => 'tareos#desaprobar'
    get 'tareos/aprobar' => 'tareos#aprobar'
    match 'tareos/tareo_semanal' => 'tareos#tareo_semanal', via: [:get, :post]
    match 'tareos/tareo_subcontratista' => 'tareos#tareo_subcontratista', via: [:get, :post]
    match 'tareos/array_subcontratos' => 'tareos#array_subcontratos', via: [:get, :post]
    match 'tareos/tareo_guardar' => 'tareos#tareo_guardar', via: [:get, :post]
    resources :tareos    
  end
  root :to => "production/inicios#index"
end

app/controllers/production/catalogcategoryworks_controller.rb
class Production::CatalogcategoryworksController < ApplicationController
  def index
    @catalogcategoryworks = Catalogcategorywork.all

    respond_to do |format|
      format.html
      format.json { render json: @catalogcategoryworks }
    end
  end

  def show
    @catalogcategorywork = Catalogcategorywork.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @catalogcategorywork }
    end
  end

  def new
    @catalogcategorywork = Catalogcategorywork.new

    respond_to do |format|
      format.html 
      format.json { render json: @catalogcategorywork }
    end
  end

  def edit
    @catalogcategorywork = Catalogcategorywork.find(params[:id])
  end

  def create
    @catalogcategorywork = Catalogcategorywork.new(catalogcategorywork_parameters)

    respond_to do |format|
      if @catalogcategorywork.save
        format.html { redirect_to production_catalogcategorywork_path(@catalogcategorywork), notice: 'catalogcategorywork was successfully created.' }
        format.json { render json: @catalogcategorywork, status: :created, location: @catalogcategorywork }
      else
        format.html { render action: "new" }
        format.json { render json: @catalogcategorywork.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @catalogcategorywork = Catalogcategorywork.find(params[:id])

    respond_to do |format|
      if @catalogcategorywork.update_attributes(catalogcategorywork_parameters)
        format.html { redirect_to production_catalogcategorywork_path(@catalogcategorywork), notice: 'catalogcategorywork was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @catalogcategorywork.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @catalogcategorywork = Catalogcategorywork.find(params[:id])
    @catalogcategorywork.destroy

    respond_to do |format|
      format.html { redirect_to production_catalogcategoryworks_url }
      format.json { head :no_content }
    end
  end

  private
  def catalogcategorywork_parameters
    params.require(:catalogcategorywork).permit(:nombre, :unit_id, :precio_unitario_normal, :precio_unitario_60, :precio_unitario_100)
  end

end

app/controllers/production/catalogofworks_controller.rb
class Production::CatalogofworksController < ApplicationController

  def index
    @catalogofworks = Catalogofwork.order('id Desc')

    respond_to do |format|
      format.html
      format.json { render json: @catalogofworks }
    end
  end

  def show
    @catalogofwork = Catalogofwork.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @catalogofwork }
    end
  end

  def new
    @catalogofwork = Catalogofwork.new

    respond_to do |format|
      format.html 
      format.json { render json: @catalogofwork }
    end
  end

  def edit
    @catalogofwork = Catalogofwork.find(params[:id])
  end

  def create
    @catalogofwork = Catalogofwork.new(catalogofwork_parameters)

    respond_to do |format|
      if @catalogofwork.save
        format.html { redirect_to production_catalogofwork_path(@catalogofwork), notice: 'catalogofwork was successfully created.' }
        format.json { render json: @catalogofwork, status: :created, location: @catalogofwork }
      else
        format.html { render action: "new" }
        format.json { render json: @catalogofwork.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @catalogofwork = Catalogofwork.find(params[:id])

    respond_to do |format|
      if @catalogofwork.update_attributes(catalogofwork_parameters)
        format.html { redirect_to production_catalogofwork_path(@catalogofwork), notice: 'catalogofwork was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @catalogofwork.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @catalogofwork = Catalogofwork.find(params[:id])
    @catalogofwork.destroy

    respond_to do |format|
      format.html { redirect_to production_catalogofworks_url }
      format.json { head :no_content }
    end
  end

  private
  def catalogofwork_parameters
    params.require(:catalogofwork).permit(:entity_id, :telefono, :movil, :direccion, :mail, :numero_cuenta, :banco, :fecha_nacimiento, :catalogcategorywork_id)
  end

end

app/controllers/production/chiefoffronts_controller.rb
class Production::ChiefoffrontsController < ApplicationController

  def index
    @chiefoffronts = Chiefoffront.all

    respond_to do |format|
      format.html
      format.json { render json: @chiefoffronts }
    end
  end


  def show
    @chiefoffront = Chiefoffront.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @chiefoffront }
    end
  end

  def new
    @chiefoffront = Chiefoffront.new

    respond_to do |format|
      format.html
      format.json { render json: @chiefoffront }
    end
  end

  
  def edit
    @chiefoffront = Chiefoffront.find(params[:id])
  end


  def create
    @chiefoffront = Chiefoffront.new(chiefoffront_parameters)

    respond_to do |format|
      if @chiefoffront.save
        format.html { redirect_to production_chiefoffront_path(@chiefoffront), notice: 'Jefedefrente was successfully created.' }
        format.json { render json: @chiefoffront, status: :created, location: @chiefoffront }
      else
        format.html { render action: "new" }
        format.json { render json: @chiefoffront.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @chiefoffront = Chiefoffront.find(params[:id])

    respond_to do |format|
      if @chiefoffront.update_attributes(chiefoffront_parameters)
        format.html { redirect_to production_chiefoffront_path(@chiefoffront), notice: 'Jefedefrente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chiefoffront.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @chiefoffront = Chiefoffront.find(params[:id])
    @chiefoffront.destroy

    respond_to do |format|
      format.html { redirect_to production_chiefoffronts_url }
      format.json { head :no_content }
    end
  end

  private
  def chiefoffront_parameters
    params.require(:chiefoffront).permit(:entity_id, :telefono, :movil_1, :movil_2, :mail, :direccion_1, :direccion_2, :foto, :nacimiento, :estado, :descripcion)
  end
end

app/controllers/production/dias_controller.rb
class Production::DiasController < ApplicationController
  def index
    @dias = Dia.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dias }
    end
  end

  def show
    @dia = Dia.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @dia }
    end
  end

  def new
    @dia = Dia.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dia }
    end
  end

  # GET /dias/1/edit
  def edit
    @dia = Dia.find(params[:id])
  end

  def create
    @dia = Dia.new(params[:dia])

    respond_to do |format|
      if @dia.save
        format.html { redirect_to @dia, notice: 'Dia was successfully created.' }
        format.json { render json: @dia, status: :created, location: @dia }
      else
        format.html { render action: "new" }
        format.json { render json: @dia.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @dia = Dia.find(params[:id])

    respond_to do |format|
      if @dia.update_attributes(params[:dia])
        format.html { redirect_to @dia, notice: 'Dia was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dia.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dia = Dia.find(params[:id])
    @dia.destroy

    respond_to do |format|
      format.html { redirect_to dias_url }
      format.json { head :no_content }
    end
  end

  private
  def dia_parameters
    params.require(:dia).permit(:nombre, :numero, :tipodedia_id)
  end
end

app/controllers/production/equipmentincludeds_controller.rb
class Production::EquipmentincludedsController < ApplicationController
  def index
    @equipmentincludeds = Equipmentincluded.all

    respond_to do |format|
      format.html 
      format.json { render json: @equipmentincludeds }
    end
  end

  def show
    @equipmentincluded = Equipmentincluded.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @equipmentincluded }
    end
  end

  def new
    @equipmentincluded = Equipmentincluded.new

    respond_to do |format|
      format.html 
      format.json { render json: @equipmentincluded }
    end
  end

  def edit
    @equipmentincluded = Equipmentincluded.find(params[:id])
  end

  def create
    @equipmentincluded = Equipmentincluded.new(equipmentincluded_parameters)

    respond_to do |format|
      if @equipmentincluded.save
        format.html { redirect_to production_equipmentincluded_path(@equipmentincluded), notice: 'equipmentincluded was successfully created.' }
        format.json { render json: @equipmentincluded, status: :created, location: @equipmentincluded }
      else
        format.html { render action: "new" }
        format.json { render json: @equipmentincluded.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @equipmentincluded = Equipmentincluded.find(params[:id])

    respond_to do |format|
      if @equipmentincluded.update_attributes(equipmentincluded_parameters)
        format.html { redirect_to production_equipmentincluded_path(@equipmentincluded), notice: 'equipmentincluded was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipmentincluded.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @equipmentincluded = Equipmentincluded.find(params[:id])
    @equipmentincluded.destroy

    respond_to do |format|
      format.html { redirect_to production_equipmentincludeds_url }
      format.json { head :no_content }
    end
  end

  private
  def equipmentincluded_parameters
    params.require(:equipmentincluded).permit(:nombre)
  end
end

app/controllers/production/inicios_controller.rb
class Production::IniciosController < ApplicationController
	def index
	end

	def inicio_parameters
		params.require(:inicio).permit()
	end

end

app/controllers/production/javascripts_controller.rb
class Production::JavascriptsController < ApplicationController
	def dynamic_states
		@states = Sectore.find(:all)
	end
end

app/views/production/phases/_form.html.erb
<%= form_for([:production,@phase], :html => {:class => "form-horizontal"}) do |f| %>

  <% if @phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
      <% @phase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <div class="control-label">
      <%= f.label :codigo %>  
    </div>
    <div class="controls">
      <%= f.text_field :codigo, :class => "span2" %>  
    </div>    
  </div>

  <div class="control-group">
    <div class="control-label">
      <%= f.label :descripcion %>  
    </div>
    <div class="controls">
      <%= f.text_field :descripcion, :class => "span5" %>  
    </div>    
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit :class => "btn btn-success" %>  
    </div>    
  </div>
<% end %>

app/views/production/phases/edit.html.erb
<div class="page-header">
	<h2>Editar Fase</h2>	
</div>


<%= render 'form' %>

<div class="form-actions">
	<%= link_to raw('<i class="icon-eye-open icon-white"></i> Ver'), production_phase_path(@phase), :class => "btn btn-info" %>
	<%= link_to raw('<i class="icon-arrow-left icon-white"></i> Regresar'), production_phases_path, :class => "btn btn-primary" %>	
</div>

app/views/production/phases/index.html.erb
<div class="row">
  <div class="span5">
    <h2>Fases</h2>
  </div>
  <div class="span3">
    <br>
    <%= link_to raw('Nuevo <i class="icon-plus icon-white"></i>'), new_production_phase_path, :class => "btn btn-primary pull-right" %> 
  </div>
</div>


<div class="row">
  <div class="span4">
    <!-- Paginacion-->
    <div class="pull-left">
      <%= will_paginate @phases, renderer: BootstrapPagination::Rails %>  
    </div>    
    <!-- End Paginacion -->    
  </div>
  <div class="span4">
    <!-- Search-->
    <%= form_tag "/subphases", :method => 'get', :class => "form-search pull-right" do %>
      <div class="input-append">    
        <%= text_field_tag :search, params[:search], :class => "span2 search-query", :placeholder => "Nombre" %>
        <%= submit_tag 'Buscar', :class => "btn" %>
      </div>
    <% end %> 
    <!-- End Search --> 
  </div>
</div><!-- End Row -->

<div class="row">
<table class="table table-striped table-bordered table-condensed table-hover   span8">
  <tr>
    <th>#id</th>
    <th>Codigo</th>
    <th>Descripcion</th>
    <th>Acciones</th>
  </tr>

<% @phases.each do |phase| %>
  <tr style="font-size:12px;">
    <td><%= phase.id %></td>
    <td><%= phase.codigo %></td>
    <td><%= phase.descripcion %></td>
    <td>
      <%= link_to raw('<i class="icon-eye-open icon-white"></i>'), [:production,phase], :class => "btn btn-small btn-info" %>
      <%= link_to raw('<i class="icon-edit icon-white"></i>'), edit_production_phase_path(phase), :class => "btn btn-small btn-success" %>
      <%= link_to raw('<i class="icon-trash icon-white"></i> '), [:production,phase], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %>
    </td>
  </tr>
<% end %>
</table>
</div>
<div class="clearfix"></div>

<div class="row">
  <div class="span8">
    <!-- Paginacion -->
      <div class="pull-right">
        <%= will_paginate @parteobras, renderer: BootstrapPagination::Rails %>  
      </div>
    <!-- End Paginacion -->
  </div>
</div>
<div class="clearfix"></div>

app/views/production/phases/new.html.erb
<div class="page-header">
	<h1>Nueva Fase</h1>	
</div>
<%= render 'form' %>

<div class="form-actions">
	<%= link_to raw('<i class="icon-arrow-left icon-white"></i> Regresar'), production_phases_path, :class => "btn btn-primary" %>
</div>

app/views/production/phases/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
	<h2>Detalle Fase</h2>
</div>

<div class="row">
<table class="table table-bordered table-striped table-condensed table-hover span8">
	<tr>
		<th>Nombre</th>
		<th>Descripcion</th>
	</tr>
	<tr>
		<td>#id</td>
		<td>Codigo</td>
	</tr>
	<tr>
		<td>Codigo</td>
		<td><%= @phase.codigo %></td>
	</tr>
	<tr>
		<td>Descripcion</td>
		<td><%= @phase.descripcion %></td>
	</tr>	
</table>
</div>
<div class="clearfix"></div>
<div class="form-actions">
	<%= link_to raw('<i class="icon-edit icon-white"></i> Editar'), edit_production_phase_path(@phase), :class => "btn btn-success" %>
	<%= link_to raw('<i class="icon-arrow-left icon-white"></i> Regresar'), production_phases_path, :class => "btn btn-primary" %>	
</div>